modelname: sslsubtab
params:
    depth: 2
    width: 1024
    dropout: 0.
    normalization: 
    activation: leakyrelu
    optimizer: AdamW
    ssl_learning_rate: 0.001
    ssl_weight_decay: 0.
    ssl_lr_scheduler: False
    le_learning_rate: 0.01
    le_weight_decay: 0.
    le_lr_scheduler: True
    le_epochs: 100
    ft_learning_rate: 0.001
    ft_weight_decay: 0.00001
    ft_lr_scheduler: True
    ft_epochs: 100
    projector: False #TableA1
    ssl_epochs: 20 #TableA1
    subsets: 4 #TableA1
    overlap: 0.75 #TableA1
    mask_ratio: 0.2 #TableA1
    noise: 0.1 #gaussian
    agg: mean