modelname: sslvime
ssl_loss: vime
params:
    depth: 2
    width: 100
    dropout: 0.
    normalization: 
    activation: relu
    optimizer: AdamW
    ssl_learning_rate: 0.01
    ssl_weight_decay: 0.
    ssl_lr_scheduler: False
    ssl_epochs: 10
    le_learning_rate: 0.01
    le_weight_decay: 0.
    le_lr_scheduler: True
    le_epochs: 100
    ft_learning_rate: 0.001
    ft_weight_decay: 0.00001
    ft_lr_scheduler: True
    ft_epochs: 100